spring:
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000;INIT=create domain if not exists jsonb as other
    username: sa
    password: sa
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
server:
  error:
    include-message: always
logging:
  level:
    edu.berkeley.bidms: DEBUG
bidms:
  log:
    directory: logs
  rest:
    matchengine:
      baseUrl: http://localhost:8080/match-engine
      person:
        url: http://localhost:8080/match-engine/person
    provision:
      baseUrl: http://localhost:8080/provisioning
      uid:
        url: http://localhost:8080/provisioning/provision/save
      new-uid:
        url: http://localhost:8080/provisioning/newUid/save
    match-service:
      baseUrl: http://notneeded
      trigger-match:
        url: http://notneeded
    downstream:
      baseUrl: http://notneeded
      provision-uid:
        url: http://notneeded
  jms-connections:
    AMQ:
      broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
      username: test
      password: test
  jms:
    downstream:
      provision-uid:
        queue-name: test.downstreamProvisionUid
    match-service:
      new-sor-object:
        queue-name: test.newSORObjectQueue
    provision:
      provision-uid:
        queue-name: notneeded
      provision-uid-bulk:
        queue-name: notneeded
      new-uid:
        queue-name: notneeded
  matchservice:
    rest:
      matchengine:
        username: test
        password: test
      provision:
        username: test
        password: test
    jms:
      match-service:
        jms-listener-container-factory-bean-name: amqJmsListenerContainerFactory
