spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000;INIT=create domain if not exists jsonb as other
    username: sa
    password: sa
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
logging:
  level:
    edu.berkeley.bidms: DEBUG
bidms:
  rest:
    matchengine:
      person:
        url: http://localhost:8080/match-engine/person
    provision:
      uid:
        url: http://localhost:8080/provisioning/provision/save
      new-uid:
        url: http://localhost:8080/provisioning/newUid/save
  jms-connections:
    AMQ:
      broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
      username: test
      password: test
  matchservice:
    rest:
      matchengine:
        username: test
        password: test
      provision:
        username: test
        password: test
    jms:
      new-sorobject:
        queue-name: test.newSORObjectQueue
