# Default settings.  Can be overridden by creating
# ${user.home}/bidms-cloudconfig/application.yml
# and adding -Dspring.config.additional-location=$HOME/bidms-cloudconfig/
# to the Java command line arguments when booting up
# the Tomcat application server.
# https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-files
server:
  # only for when using embedded application server
  port: 8888
spring:
  application:
    name: bidms-config
  cloud:
    config:
      server:
        git:
          uri: file:${user.home}/bidms-config-repo
          timeout: 20
  security:
    user:
      name: user
      password: configureme
bidms:
  log:
    directory: logs
