spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000;INIT=create domain if not exists jsonb as json
    username: sa
    password: sa
logging:
  level:
    edu.berkeley.bidms: TRACE
bidms:
  rest:
    matchengine:
      baseUrl: http://notneeded
      person:
        url: http://notneeded
    provision:
      baseUrl: http://notneeded
      uid:
        url: http://notneeded
      new-uid:
        baseUrl: http://notneeded
        url: http://notneeded
  matchengine:
    match-config: classpath:/TestMatchConfig.groovy
