spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000;INIT=create domain if not exists jsonb as json
    username: sa
    password: sa
server:
  error:
    include-message: always
logging:
  level:
    edu.berkeley.bidms: TRACE
bidms:
  rest:
    matchengine:
      baseUrl: http://notneeded
      person:
        url: http://notneeded
    provision:
      baseUrl: http://notneeded
      uid:
        url: http://notneeded
      new-uid:
        baseUrl: http://notneeded
        url: http://notneeded
    match-service:
      baseUrl: http://notneeded
      trigger-match:
        url: http://notneeded
  jms:
    downstream:
      provision-uid:
        queue-name: notneeded
    match-service:
      new-sor-object:
        queue-name: notneeded
    provision:
      provision-uid:
        queue-name: notneeded
      provision-uid-bulk:
        queue-name: notneeded
      new-uid:
        queue-name: notneeded
  matchengine:
    match-config: classpath:/TestMatchConfig.groovy
